name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for NPM provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish @owenbush/ableton-inspector-core
        run: npm publish --workspace=@owenbush/ableton-inspector-core --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @owenbush/ableton-inspector
        run: npm publish --workspace=@owenbush/ableton-inspector --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Successfully published packages to NPM"
          echo "Core: https://www.npmjs.com/package/@owenbush/ableton-inspector-core"
          echo "CLI: https://www.npmjs.com/package/@owenbush/ableton-inspector"

